#!/bin/sh

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

. $SCRIPT_DIR/utils.sh

# Welcome to the thoughtbot laptop script (Fedora edition)!
# Be prepared to turn your machine
# into an awesome development machine.

# shellcheck disable=SC2154
trap 'ret=$?; test $ret -ne 0 && printf "failed\\n\\n" >&2; exit $ret' EXIT

set -e

if [ ! -d "$HOME/.bin/" ]; then
  mkdir "$HOME/.bin"
fi

update_shell() {
  local shell_path
  shell_path="/usr/bin/zsh"

  fancy_echo "Changing your shell to zsh ..."
  if ! grep "$shell_path" /etc/shells >/dev/null 2>&1; then
    fancy_echo "Installing zsh package"
    sudo dnf install -y zsh
  fi
  sudo chsh -s "$shell_path" "$USER"
}

case "$SHELL" in
*/zsh) ;;
*)
  update_shell
  ;;
esac

fancy_echo "Updating dnf repositories ..."
sudo dnf check-update || true

fancy_echo "Installing core packages via dnf ..."
sudo dnf install -y \
  bison \
  bzip2 \
  chromium \
  coreutils \
  ctags \
  fish \
  flex \
  gawk \
  gcc-c++ \
  gdbm-devel \
  git \
  gnupg2 \
  hostname \
  keychain \
  libatomic \
  libffi-devel \
  libuuid-devel \
  libyaml-devel \
  lynx \
  make \
  ncurses-devel \
  openssl \
  openssl-devel \
  patch \
  perl-core \
  pinentry-curses \
  poppler-utils \
  rcm \
  readline-devel \
  shellcheck \
  socat \
  util-linux-user \
  vips \
  xz \
  zlib-devel

install_mise
