#!/bin/sh

# Welcome to the thoughtbot laptop script (NixOS edition)!
# Be prepared to turn your machine
# into an awesome development machine.

trap 'ret=$?; test $ret -ne 0 && printf "failed\\n\\n" >&2; exit $ret' EXIT

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

. $SCRIPT_DIR/utils.sh

if [ ! -d "$HOME/.bin/" ]; then
  mkdir "$HOME/.bin"
fi

fancy_echo "Applying NixOS Flake configuration ..."
sudo nixos-rebuild switch --flake "$SCRIPT_DIR/nixos-setup#nixos-laptop"
