[tools]
usage = "latest"
minio = "latest"
node = "latest"
rust = "latest"
lua = "5.1"
ruby = "latest"
postgres = "latest"
redis = "latest"
neovim = "latest"
tmux = "latest"
fzf = "latest"
github-cli = "latest"
tree-sitter = "latest"
zoxide = "latest"
direnv = "latest"
ripgrep = "latest"
fd = "latest"
