[tools]
ast-grep = "latest"
direnv = "latest"
fd = "latest"
fzf = "latest"
gem:overmind = "latest"
github-cli = "latest"
lua = "5.1"
minio = "latest"
neovim = "latest"
node = "latest"
postgres = "latest"
redis = "latest"
ripgrep = "latest"
ruby = "latest"
rust = "latest"
tmux = "latest"
tree-sitter = "latest"
usage = "latest"
zoxide = "latest"
